### ISSUE TITLE
A possible typo in .CRO file parser

### ISSUE THREAD

**Issue by mentaljam** [KUL-RSDA/AquaCrop#343]
Looks like a COPY-PASTE typo in condition. I suppose it should be `< 70`

https://github.com/KUL-RSDA/AquaCrop/blob/6b242b6650bce6f1387668aa30f40f0c293a4b8d/src/global.f90#L5158-L5159

**Comment by mbechtold** [comment]
Thanks for pointing this out. Indeed a confusing comment but no bug.
Note: Version 6.2 was never released (the update of version 6.1 to 6.2 became so all-encompassing (and took so long since we kept adding new things) that it was decided to release the new version of AquaCrop as Version 7.0. So it could equally be "70" here without any effect.
